### ISSUE TITLE
Error when initializing `lunr.th.js`

### ISSUE THREAD

**Issue by jinyoungbang** [MihaiValentin/lunr-languages#101]
When initializing `lunr.th.js`, the following error occurs: `TypeError: Cannot read properties of undefined (reading 'init')`.

This seems to be happening to languages that try to use `wordcut.js`, where the error occurs as the `init()` function gets called, as shown in this block:

```js
var segmenter = lunr.wordcut;
segmenter.init();
```

Personally, I think that the `wordcut.js` is not getting imported into the respective languages and with absolute import, no error seems to occur:

```js
lunr.wordcut = require('./wordcut');
var segmenter = lunr.wordcut;
segmenter.init();
```

Would love to get some advice or feedback if this would be the right approach to solve the issue!

**Comment by rennerg** [comment]
I'm having the same problem with `lunr.hi.js`

**Comment by andrew-polk** [comment]
Note that while I am using docusaurus v2, this error occurs with v3 as well.
I used https://docusaurus.new/, just added the dependency, and added 
```
  themes: [
    [
      require.resolve("@easyops-cn/docusaurus-search-local"),
      {
        language: ["en", "hi"]
      },
    ],
  ],
```
to the config. 

That gave:  
```
[ERROR] Error: Unable to build website for locale en.
    at tryToBuildLocale (/project/workspace/node_modules/@docusaurus/core/lib/commands/build.js:54:19)
    at async /project/workspace/node_modules/@docusaurus/core/lib/commands/build.js:65:9
    at async mapAsyncSequential (/project/workspace/node_modules/@docusaurus/utils/lib/jsUtils.js:20:24)
    at async Command.build (/project/workspace/node_modules/@docusaurus/core/lib/commands/build.js:63:5) {
  [cause]: TypeError: Cannot read properties of undefined (reading 'init')
      at server.bundle.js:16693:15
      at 1088 (server.bundle.js:14194:70)
      at __webpack_require__ (server.bundle.js:28127:42)
      at 7401 (server.bundle.js:11585:24)
      at __webpack_require__ (server.bundle.js:28127:42)
      at 7489 (server.bundle.js:8814:14)
      at __webpack_require__ (server.bundle.js:28127:42)
      at 6533 (server.bundle.js:9695:21)
      at __webpack_require__ (server.bundle.js:28127:42)
      at server.bundle.js:28193:37
}
```
