### ISSUE TITLE
multi language with English and Chinese not work

### ISSUE THREAD

**Issue by Tasselmi** [MihaiValentin/lunr-languages#116]
I have an error here. Don't know why.

```
lunr.zh.js:98 Uncaught TypeError: Cannot read properties of undefined (reading 'cut')
    at lunr.zh.tokenizer (lunr.zh.js:98:17)
    at lunr.Builder.tokenizer (archive/?q=jekyll:686:49)
    at lunr.Builder.add (lunr.js:2479:25)
    at lunr.Builder.<anonymous> (archive/?q=jekyll:696:14)
    at Array.forEach (<anonymous>)
    at lunr.Builder.<anonymous> (archive/?q=jekyll:695:15)
    at lunr (lunr.js:53:12)
    at archive/?q=jekyll:680:11
```

please help me. Thanks.

**Comment by MoonS11** [comment]
你可能需要安装 @node-rs/jieba

**Comment by MihaiValentin** [comment]
Fixed in 1.15.0. Please update package.
